---
- name: check if admin user's node directory exists
  file:
    path: "{{ node_directory }}"
    state: directory
    mode: 0755
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  tags: algorand-node-setup

- name: check if Ansible temporary user directory exists
  file:
    path: "/home/{{ admin_user }}/.ansible/tmp"
    state: directory
    mode: 0700
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  tags: algorand-node-setup

- name: download the updater script
  get_url:
    url: https://raw.githubusercontent.com/algorand/go-algorand-doc/master/downloads/installers/update.sh
    dest: "{{ node_directory }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755
  become: yes
  register: updater_downloaded
  tags: algorand-node-setup

- name: run the installer
  shell: "./update.sh -i -c stable -p {{ node_directory }} -d {{ node_directory }}/data -n"
  args:
    chdir: "{{ node_directory }}"
  become: yes
  become_user: "{{ admin_user }}"
  when: updater_downloaded.changed
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to user's .bashrc
  lineinfile:
    dest: "/home/{{ admin_user }}/.bashrc"
    line: "{{ item }}"
    state: present
  become: yes
  become_user: "{{ admin_user }}"
  with_items:
    - 'export ALGORAND_DATA="{{ node_directory }}/data"'
    - 'export PATH="{{ node_directory }}:$PATH"'
  tags: algorand-node-setup
