---
- name: download the updater script
  get_url:
    url: https://raw.githubusercontent.com/algorand/go-algorand-doc/master/downloads/installers/update.sh
    dest: "{{ node_directory }}/update_by_ansible.sh"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755
  register: updater_downloaded
  tags: algorand-node-setup

- name: copy newer updater script
  copy:
    src: "{{ node_directory }}/update_by_ansible.sh"
    dest: "{{ node_directory }}/update.sh"
    remote_src: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    mode: 0755
  when: updater_downloaded.changed
  register: updater_file
  tags: algorand-node-setup

- name: remove sudo prefix in updater script for Debian
  replace:
    path: "{{ node_directory }}/update.sh"
    regexp: "sudo -n systemctl"
    replace: "systemctl"
  become: yes
  become_user: "{{ admin_user }}"
  when: updater_downloaded.changed and os_distribution == "Debian"
  tags: algorand-node-setup

- name: run the installer
  shell: "yes 'y' | ./update.sh -i -c stable -p {{ node_directory }} -d {{ node_directory }}/data -n"
  args:
    chdir: "{{ node_directory }}"
  become: yes
  become_user: "{{ admin_user }}"
  when: updater_file.changed
  tags: algorand-node-setup
