all:
  hosts:
    fedora:
      ansible_host: 192.168.1.80
    debian:
      ansible_host: 192.168.1.81
    ubuntu:
      ansible_host: 192.168.1.82
    opensuse:
      ansible_host: 192.168.1.83
    manjaro:
      ansible_host: 192.168.1.86
    rocky:
      ansible_host: 192.168.1.87
    almalinux:
      ansible_host: 192.168.1.88
    oracle:
      ansible_host: 192.168.1.89
    mageia:
      ansible_host: 192.168.1.90
    centos7:
      ansible_host: 192.168.1.91
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    macos:
      hosts:
        catalina:
          ansible_host: 192.168.1.84
      vars:
        ansible_user: algonaut
    windows:
      hosts:
        win10:
          ansible_host: 192.168.1.85
      vars:
        ansible_user: algonaut
        ansible_connection: ssh
        ansible_shell_type: cmd
