---
# SETUP
- name: setup user and distro information
  import_playbook: setup_playbook.yml

# INSTALL NODE AND SERVICE
- name: install using package manager
  hosts: all:!windows:!macos
  remote_user: "{{ admin_user }}"
  roles:
    - role: install_deb
      when: not updater_install and os_family == "Debian"
    - role: install_rpm
      when: not updater_install and os_distribution == "CentOS"
    # # FIXME https://github.com/algorand/go-algorand/issues/1489#issuecomment-875033099
    #   when: not updater_install and os_family in ("Suse", "RedHat")

- name: install using updater script
  hosts: all:!windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: install_other
      when: updater_install
    - role: update_setup
      when: updater_install

- name: install using installation binary
  hosts: windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: install_win

# POST-INSTALL CONFIGURATION
- name: node configuration
  hosts: all
  remote_user: "{{ admin_user }}"
  roles:
    - role: network_configuration
      when: os_family != "Windows"
    - role: node_sync
      when: fast_catchup
    - role: telemetry
      when: os_family != "Windows"
