---
- name: retrieve OS data
  hosts: all
  remote_user: root
  roles:
     - role: distrofacts

- name: create admin_user
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: createuser

- name: install and configure using package manager
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: install_deb
      when: use_package_manager and os_family == "Debian"
    # - role: install_rpm
    #   when: use_package_manager and os_family == "RedHat"

- name: install and configure using updater script
  hosts: all:!windows
  remote_user: root
  vars:
    # use_updater: not use_package_manager or os_family not in ("Debian", "RedHat")
    use_updater: not use_package_manager or os_family not in ("Debian", )
  roles:
    - role: install_other
      when: use_updater
    - role: systemd_service
      when: use_updater and os_family != "Darwin"
    - role: launchd_daemon
      when: use_updater and os_family == "Darwin"

- name: install and configure using installation binary
  hosts: windows
  remote_user: root
  roles:
    - role: install_win

- name: switch network
  hosts: all:!windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: switch_network
      when: algorand_network != "mainnet"

- name: fast node catchup
  hosts: all
  remote_user: "{{ admin_user }}"
  roles:
    - role: node_sync
      when: fast_catchup

- name: setup node updating
  hosts: all:!windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: update_setup
      # when: not use_package_manager or os_family not in ("Debian", "RedHat")
      when: not use_package_manager or os_family not in ("Debian", )
