---
- name: retrieve OS data
  hosts: all
  remote_user: root
  roles:
     - role: distrochecks

- name: create admin_user
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: createuser

- name: install and configure using package manager
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: install_deb
      when: not updater_install and os_family == "Debian"
    - role: install_rpm
      when: not updater_install and os_distribution == "CentOS"
    # # FIXME https://github.com/algorand/go-algorand/issues/1489#issuecomment-875033099
    #   when: not updater_install and os_family in ("Suse", "RedHat")

- name: install and configure using updater script
  hosts: all:!windows
  remote_user: root
  roles:
    - role: install_other
      when: updater_install
    - role: systemd_service
      when: updater_install and os_family not in ("Darwin", "Alpine")
    - role: launchd_daemon
      when: updater_install and os_family == "Darwin"
    - role: openrc_service
      when: updater_install and os_family == "Alpine"
    - role: update_setup
      when: updater_install

- name: install and configure using installation binary
  hosts: windows
  remote_user: root
  roles:
    - role: install_win

- name: configure network
  hosts: all:!windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: network_configuration

- name: fast node catchup and telemetry setup
  hosts: all
  remote_user: "{{ admin_user }}"
  roles:
    - role: node_sync
      when: fast_catchup
    - role: telemetry
