---
- name: retrieve OS data
  hosts: all
  remote_user: root
  roles:
     - role: distrochecks

- name: create admin_user
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: createuser

- name: install and configure using package manager
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: install_deb
      when: not updater_install and os_family == "Debian"
    # - role: install_rpm
    #   when: not updater_install and os_family == "RedHat"

- name: install and configure using updater script
  hosts: all:!windows
  remote_user: root
  roles:
    - role: install_other
      when: updater_install
    - role: systemd_service
      when: updater_install and os_family != "Darwin"
    - role: launchd_daemon
      when: updater_install and os_family == "Darwin"
    - role: update_setup
      when: updater_install

- name: install and configure using installation binary
  hosts: windows
  remote_user: root
  roles:
    - role: install_win

- name: configure network
  hosts: all:!windows
  remote_user: "{{ admin_user }}"
  roles:
    - role: network_configuration

- name: fast node catchup and telemetry setup
  hosts: all
  remote_user: "{{ admin_user }}"
  roles:
    - role: node_sync
      when: fast_catchup
    - role: telemetry
