---
- name: retrieve OS data
  hosts: all
  remote_user: root
  roles:
     - role: distrofacts

- name: create admin_user
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: createuser

- name: single machine provisioning for Algorand
  hosts: all
  remote_user: root
  roles:
    - role: algorand_deb
      when: use_package_manager and os_family == "Debian"
    - role: algorand_rpm
      when: use_package_manager and os_family == "RedHat"
    - role: algorand_other
      when: not use_package_manager or os_family not in ("Debian", "RedHat")
