---
- name: retrieve OS data
  hosts: all
  remote_user: root
  roles:
     - role: distrofacts

- name: create admin_user
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: createuser

- name: install and configure using package manager
  hosts: all:!windows:!macos
  remote_user: root
  roles:
    - role: install_deb
      when: use_package_manager and os_family == "Debian"
    - role: install_rpm
      when: use_package_manager and os_family == "RedHat"

- name: install and configure using updater script
  hosts: all:!windows
  remote_user: root
  vars:
    # use_updater: not use_package_manager or os_family not in ("Debian", "RedHat")
    use_updater: not use_package_manager or os_family not in ("Debian", )
  roles:
    - role: install_other
      when: use_updater
    - role: systemd_service
      when: use_updater and os_family != "Darwin"
    - role: launchd_daemon
      when: use_updater and os_family == "Darwin"

- name: install and configure using installation binary
  hosts: windows
  remote_user: root
  roles:
    - role: install_win
