---
- name: check if node data directory exists
  file:
    path: "{{ node_data_directory }}"
    state: directory
    mode: 0755
    owner: "{{ goal_user }}"
    group: "{{ goal_user_group }}"
  become: yes
  when: not common_data_directory
  tags: network-configuration

- include: betanet_configuration.yml
  when: algorand_network == "betanet"

- include: package_manager_switch.yml
  when: not updater_install

- include: updater_switch.yml
  when: updater_install
