---
- name: wait until the file algod.net is present in the node data directory
  wait_for:
    path: "{{ node_directory }}/data/algod.net"
  tags: network-configuration

- name: register node status as variable
  shell: "./goal node status -d {{ node_directory }}/data"
  args:
    chdir: "{{ node_directory }}"
  register: node_status_network
  changed_when: false
  tags: network-configuration

- name: set network switching Boolean variable
  set_fact:
    need_network_switch: 'algorand_network|string not in node_status_network.stdout'
  tags: network-configuration

- include: betanet_configuration.yml
  when: need_network_switch and algorand_network == "betanet"

- include: package_manager_switch.yml
  # when: need_network_switch and use_package_manager and os_family in ("Debian", "RedHat")
  when: need_network_switch and use_package_manager and os_family in ("Debian", )

- include: other_switch.yml
  # when: need_network_switch and (not use_package_manager or os_family not in ("Debian", "RedHat"))
  when: need_network_switch and (not use_package_manager or os_family not in ("Debian", ))
