---
- name: copy Algorand network genesis file to data directory
  copy:
    src: "{{ node_data_directory }}genesis/{{ algorand_network }}/genesis.json"
    dest: "{{ node_data_directory }}genesis.json"
    remote_src: yes
    owner: "{{ goal_user }}"
    group: "{{ goal_user_group }}"
    mode: 0644
  become: yes
  notify: "network switched (package manager)"
  tags: switch-network
