---
- name: copy Algorand network genesis file to data directory
  copy:
    src: "{{ node_directory }}genesisfiles/{{ algorand_network }}/genesis.json"
    dest: "{{ node_data_directory }}genesis.json"
    remote_src: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0644
  become: yes
  notify: "network switched (updater)"
  tags: switch-network

- name: overwrite existing Algorand OpenRC service
  template:
    src: algorand.rc
    dest: /etc/init.d/algorand
    owner: root
    group: root
    mode: 0755
  become: yes
  when: not common_data_directory and os_family == "Alpine"
  notify: "network switched (updater)"
  tags: switch-network

- name: install Algorand node daemon script
  template:
    src: org.algorand.daemon.plist.jinja
    dest: /Library/LaunchDaemons/org.algorand.daemon.plist
    owner: root
    group: wheel
    mode: 0644
  become: yes
  when: not common_data_directory and os_family == "Darwin"
  notify: "network switched (updater)"
  tags: switch-network
