---
- name: copy Algorand network genesis file to data directory
  copy:
    src: "{{ node_directory }}genesisfiles/{{ algorand_network }}/genesis.json"
    dest: "{{ node_data_directory }}genesis.json"
    remote_src: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0644
  become: yes
  notify: "network switched (updater)"
  tags: switch-network
