---
- name: create admin_user
  user:
    name: "{{ admin_user }}"
    state: present
    createhome: yes
    shell: /bin/bash
  tags: createuser

# - name: allow user to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     line: '{{ admin_user }} ALL=(ALL) NOPASSWD: ALL'
#     validate: 'visudo -cf %s'
#   become: yes
#   when: os_distribution != "Debian"
#   tags: createuser

- name: set up authorized keys for the user
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ item }}"
  with_file:
    - ~/.ssh/id_rsa.pub
  ignore_errors: yes
  tags: createuser
