---
- name: download the updater script
  get_url:
    url: https://raw.githubusercontent.com/algorand/go-algorand-doc/master/downloads/installers/update.sh
    dest: "{{ node_directory }}update_by_ansible.sh"
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0755
  notify:
    - "download updater"
    - "setup service (updater)"
  tags: algorand-node-setup

- name: escape service name
  command: "systemd-escape {{ node_data_directory }}"
  become: yes
  register: systemd_escape_directory
  changed_when: false
  when: os_family not in ("Darwin", "Alpine")
  tags: algorand-node-setup

- name: set escaped service name as variable
  set_fact:
    systemd_escaped_service_name: "{{ systemd_escape_directory.stdout }}"
  when: os_family not in ("Darwin", "Alpine")
  tags: algorand-node-setup
