---
- name: add Algorand environment variables exporting to admin user's .bash_profile
  lineinfile:
    dest: "{{ admin_home_directory }}.bash_profile"
    line: "{{ item }}"
    state: present
    create: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0644
  with_items:
    - 'export ALGORAND_DATA="{{ node_data_directory }}"'
    - 'export PATH="{{ node_directory }}:$PATH"'
  when: os_family != "Darwin"
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to admin user's .zshrc
  lineinfile:
    dest: "{{ admin_home_directory }}.zshrc"
    line: "{{ item }}"
    state: present
    create: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0644
  with_items:
    - 'export ALGORAND_DATA="{{ node_data_directory }}"'
    - 'export PATH="{{ node_directory }}:$PATH"'
  when: os_family == "Darwin"
  tags: algorand-node-setup
