---
- name: add Algorand environment variables exporting to admin user's .bash_profile
  lineinfile:
    dest: "{{ admin_home_directory }}/.bash_profile"
    line: "{{ item }}"
    state: present
    create: yes
  become: yes
  become_user: "{{ admin_user }}"
  with_items:
    - 'export ALGORAND_DATA="{{ node_data_directory }}"'
    - 'export PATH="{{ node_directory }}:$PATH"'
  when: os_family != "Darwin"
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to admin user's .zshrc
  lineinfile:
    dest: "{{ admin_home_directory }}/.zshrc"
    line: "{{ item }}"
    state: present
    create: yes
  become: yes
  become_user: "{{ admin_user }}"
  with_items:
    - 'export ALGORAND_DATA="{{ node_data_directory }}"'
    - 'export PATH="{{ node_directory }}:$PATH"'
  when: os_family == "Darwin"
  tags: algorand-node-setup

- name: change systemd service directory in systemd-setup for openSUSE
  replace:
    path: "{{ node_directory }}/systemd-setup.sh"
    regexp: "/lib/systemd/system/algorand@.service"
    replace: "/usr/lib/systemd/system/algorand@.service"
  become: yes
  become_user: "{{ admin_user }}"
  when: os_family == "Suse"
  tags: algorand-node-setup
