---
- name: check if node directory exists
  file:
    path: "{{ node_directory }}"
    state: directory
    mode: 0755
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
  tags: algorand-node-setup

- name: install dependencies for Debian
  apt:
    name: curl
    state: present
  when: os_distribution == "Debian"
  tags: algorand-node-dependencies

- name: set Algorand executables shell command variables
  set_fact:
    goal_user: "{{ admin_user }}"
    goal_user_group: "{{ admin_user_group }}"
    goal_executable: "./goal"
    diagcfg_executable: "./diagcfg"
  tags: distrochecks