---
- name: copy newer updater script
  copy:
    src: "{{ node_directory }}update_by_ansible.sh"
    dest: "{{ node_directory }}update.sh"
    remote_src: yes
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0755
  listen: "download updater"

- name: run the installer
  shell: "yes 'y' | ./update.sh -i -c stable -p {{ node_directory }} -d {{ node_data_directory }} -n"
  args:
    chdir: "{{ node_directory }}"
  listen: "download updater"

- name: change systemd service directory in systemd-setup for openSUSE
  replace:
    path: "{{ node_directory }}systemd-setup.sh"
    regexp: "> /lib/systemd/system/algorand@.service"
    replace: "> /usr/lib/systemd/system/algorand@.service"
  when: os_family == "Suse"
  listen: "download updater"

- name: create Algorand node systemd service
  command: "./systemd-setup.sh {{ admin_user }} {{ admin_user }}"
  args:
    chdir: "{{ node_directory }}"
  become: yes
  when: os_family not in ("Darwin", "Alpine")
  listen: "setup service (updater)"

- name: install Algorand node daemon script
  template:
    src: org.algorand.daemon.plist.jinja
    dest: /Library/LaunchDaemons/org.algorand.daemon.plist
    owner: root
    group: wheel
    mode: 0644
  become: yes
  when: os_family == "Darwin"
  listen: "setup service (updater)"

- name: install Algorand node OpenRC startup script
  template:
    src: algorand.rc
    dest: /etc/init.d/algorand
    owner: root
    group: root
    mode: 0755
  become: yes
  when: os_family == "Alpine"
  listen: "setup service (updater)"

- name: enable and start Algorand systemd service
  systemd:
    name: "algorand@{{ systemd_escaped_service_name }}"
    state: started
    enabled: yes
  become: yes
  when: os_family not in ("Darwin", "Alpine")
  listen: "setup service (updater)"

- name: enable and start Algorand node daemon
  community.general.launchd:
    name: org.algorand.daemon
    state: started
    enabled: yes
  become: yes
  when: os_family == "Darwin"
  listen: "setup service (updater)"

- name: enable and start Algorand node OpenRC service
  service:
    name: algorand
    state: started
    enabled: yes
  become: yes
  when: os_family == "Alpine"
  listen: "setup service (updater)"
