---
## COMMON GLOBAL VARIABLES
# default administrator user on the host machine(s)
admin_user: algonaut
admin_user_group: "{{ admin_user }}"

# identity used to connect to host machine(s)
local_path_to_public_key: ~/.ssh/id_rsa.pub

## NODE
# Algorand network configuration
algorand_network: "testnet"
fast_catchup: true

# installation by system package manager
use_package_manager: true
install_algorand_devtools: true

# installation by updater script
node_directory: "{{ admin_home_directory }}node/"
node_data_directory: "{{ node_directory }}data/"
common_data_directory: false
systemd_timer_update: false

# installation in Windows
algorand_version: ""  # leave empty for the latest

# setup telemetry
enable_telemetry: false
use_hostname_for_telemetry: true
fixed_name_for_telemetry: ""

## SANDBOX
docker_compose_version: 1.29.2
sandbox_directory: "{{ admin_home_directory }}sandbox/"
