---
project_name: algorand-provisioning
admin_user: algonaut
admin_user_group: "{{ admin_user }}"
admin_email: algonaut@example.com
admin_home_directory: "/home/{{ admin_user }}"
node_directory: "{{ admin_home_directory }}/node"

use_package_manager: false
install_algorand_devtools: true
algorand_network: "testnet"
fast_catchup: true
algorand_version: 2.7.1  # for retrieving Windows installation binary

enable_telemetry: false
# Use machine's hostname
use_hostname_for_telemetry: false
# Set fixed hostname or leave empty to disable providing a hostname
fixed_hostname_for_telemetry: ""
