---
# default administrator user on the host machine(s)
admin_user: algonaut
admin_user_group: "{{ admin_user }}"

# identity used to connect to host machine(s)
local_path_to_public_key: ~/.ssh/id_rsa.pub

# installation by system package manager
use_package_manager: true
install_algorand_devtools: true

# installation by updater script
node_directory: "{{ admin_home_directory }}node/"
node_data_directory: "{{ node_directory }}data/"

# installation in Windows
algorand_version: ""  # leave empty for the latest

# Algorand network configuration
algorand_network: "testnet"
fast_catchup: true

# setup telemetry
enable_telemetry: false
use_hostname_for_telemetry: true
fixed_name_for_telemetry: ""
