---
# Here are variables common to all hosts
project_name: algorand-provisioning
admin_user: pythonista
admin_user_group: "{{ admin_user }}"
admin_email: pythonista@example.com
admin_home_directory: "/home/{{ admin_user }}"
node_directory: "{{ admin_home_directory }}/node"

use_package_manager: false
algorand_service: "system"  # user

install_algorand_devtools: true
algorand_network: "testnet"
