---
- name: install Algorand daemon script
  template:
    src: org.algorand.daemon.plist.jinja
    dest: /Library/LaunchDaemons/org.algorand.daemon.plist
    owner: root
    group: wheel
    mode: 0644
  become: yes
  tags: algorand-service

- name: enable Algorand node daemon
  community.general.launchd:
    name: org.algorand.daemon
    state: started
    enabled: yes
  become: yes
  tags: algorand-service
