---
- name: create system-wide systemd service
  shell: "./systemd-setup.sh {{ admin_user }} {{ admin_user }}"
  args:
    chdir: "{{ node_directory }}"
  when: updater_file.changed
  become: yes
  tags: algorand-service

- name: enable algorand systemd service
  shell: "systemctl enable algorand@$(systemd-escape {{ node_directory }}/data)"
  when: updater_file.changed
  become: yes
  tags: algorand-service

- name: start algorand systemd service
  shell: "systemctl start algorand@$(systemd-escape {{ node_directory }}/data)"
  when: updater_file.changed
  become: yes
  tags: algorand-service
