---
- name: change some variables when using package manager
  set_fact:
    goal_user: algorand
    goal_user_group: algorand
    node_directory: /var/lib/algorand
    node_data_directory: /var/lib/algorand
    goal_executable: "goal"
    diagcfg_executable: "diagcfg"
  tags: algorand-node-setup

- name: install system dependencies for Algorand node
  apt:
    name:
      - gnupg2
      - curl
      - software-properties-common
    state: present
  tags: algorand-node-setup

- name: add Algorand apt-key
  apt_key:
    url: https://releases.algorand.com/key.pub
    state: present
  tags: algorand-node-setup

- name: add Algorand APT repository
  apt_repository:
    repo: deb [arch=amd64] https://releases.algorand.com/deb/ stable main
    state: present
    filename: 'algorand-node'
  tags: algorand-node-setup

- name: install Algorand node and devtools
  apt:
    name: algorand-devtools
    state: present
  when: install_algorand_devtools
  tags: algorand-node-setup

- name: install Algorand node without devtools
  apt:
    name: algorand
    state: present
  when: not install_algorand_devtools
  tags: algorand-node-setup

- name: ensure Algorand node installation was successful
  command: algod -v
  changed_when: false
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to admin user's .bash_profile
  lineinfile:
    dest: "{{ admin_home_directory }}/.bash_profile"
    line: 'export ALGORAND_DATA="{{ node_data_directory }}"'
    state: present
    create: yes
  become: yes
  become_user: "{{ admin_user }}"
  tags: algorand-node-setup
