---
- name: create daily update check cronjob
  cron:
    weekday: "*"
    hour: "22"
    minute: "30"
    name: "Algorand node update (daily schedule)"
    job: ": Algorand node update ; {{ node_directory }}update.sh -d {{ node_data_directory }} > {{ node_directory }}update.log 2>&1"
  become: yes
  become_user: "{{ admin_user }}"
  tags: update-setup
