---
- name: change some variables when using package manager
  set_fact:
    goal_user: algorand
    goal_user_group: algorand
    node_directory: /var/lib/algorand/
    node_data_directory: /var/lib/algorand/
  tags: algorand-node-setup

- name: add Algorand rpm-key
  ansible.builtin.rpm_key:
    key: https://releases.algorand.com/rpm/rpm_algorand.pub
    state: present
  become: yes
  tags: algorand-node-setup

- include: dnf_install.yml
  when: os_family == "RedHat" and not (os_distribution == "CentOS" and os_version is version("8", "<"))

- include: yum_install.yml
  when: os_distribution == "CentOS" and os_version is version("8", "<")

- include: zypper_install.yml
  when: os_family == "Suse"

- name: ensure Algorand node installation was successful
  command: algod -v
  changed_when: false
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to admin user's .bash_profile
  lineinfile:
    dest: "{{ admin_home_directory }}.bash_profile"
    line: 'export ALGORAND_DATA="{{ node_data_directory }}"'
    state: present
    create: yes
  tags: algorand-node-setup
