---
- name: set node_directory variable
  set_fact:
    node_directory: /var/lib/algorand
  tags: algorand-node-setup

# - name: install system dependencies for Algorand node
#   dnf:
#     name:
#       - yum-cron
#     state: present
#   tags: algorand-node-setup

- name: add Algorand rpm-key
  ansible.builtin.rpm_key:
    key: https://releases.algorand.com/rpm/rpm_algorand.pub
    state: present
  tags: algorand-node-setup

- name: add Algorand YUM repository
  ansible.builtin.yum_repository:
    name: algorand
    description: Algorand node
    file: algorand
    baseurl: https://releases.algorand.com/rpm/stable
  tags: algorand-node-setup

- name: install Algorand node and devtools
  dnf:
    name: algorand-devtools
    state: present
  when: "install_algorand_devtools|bool"
  tags: algorand-node-setup

- name: install Algorand node without devtools
  dnf:
    name: algorand.x86_64
    state: present
  when: "not install_algorand_devtools|bool"
  tags: algorand-node-setup

- name: ensure Algorand node installation was successful
  command: algod -v
  changed_when: false
  tags: algorand-node-setup

- name: add Algorand environment variables exporting to admin user's .bash_profile
  lineinfile:
    dest: "{{ admin_home_directory }}/.bash_profile"
    line: "{{ item }}"
    state: present
    create: yes
  become: yes
  become_user: "{{ admin_user }}"
  with_items:
    - 'export ALGORAND_DATA="{{ node_directory }}/data"'
  tags: algorand-node-setup
