---
- name: install system dependencies for Algorand node
  yum:
    name: dnf-automatic
    state: present
  become: yes
  when: os_distribution == "CentOS" and os_version is version("7", ">")
  tags: algorand-node-setup

- name: add Algorand YUM repository
  ansible.builtin.yum_repository:
    name: algorand
    description: Algorand node
    file: algorand
    baseurl: https://releases.algorand.com/rpm/stable
  become: yes
  tags: algorand-node-setup, install-rpm, yum-install

- name: install Algorand node and devtools
  yum:
    name: algorand-devtools
    state: present
  become: yes
  when: install_algorand_devtools
  tags: algorand-node-setup, install-rpm, yum-install

- name: install Algorand node without devtools
  yum:
    name: algorand
    state: present
  become: yes
  when: not install_algorand_devtools
  tags: algorand-node-setup, install-rpm, yum-install

- name: ensure Algorand service is enabled and started
  systemd:
    name: algorand
    state: started
    enabled: yes
  become: yes
  tags: algorand-node-setup, install-rpm, yum-install
