---
- name: install system dependencies for Algorand node
  zypper:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - dnf-automatic
    - shadow-utils  # won't install
  tags: algorand-node-setup

- name: add Algorand Zypper repository
  community.general.zypper_repository:
    description: Algorand node
    repo: https://releases.algorand.com/rpm/stable/algorand.repo
  become: yes
  tags: algorand-node-setup, install-rpm, zypper-install

- name: install Algorand node and devtools
  zypper:
    name: algorand-devtools
    state: present
  become: yes
  when: install_algorand_devtools
  tags: algorand-node-setup, install-rpm, zypper-install

- name: install Algorand node without devtools
  dnf:
    name: algorand
    state: present
  become: yes
  when: not install_algorand_devtools
  tags: algorand-node-setup, install-rpm, zypper-install
