---
- name: retrieve the latest catchpoint
  get_url:
    url: "https://algorand-catchpoints.s3.us-east-2.amazonaws.com/channel/{{ algorand_network }}/latest.catchpoint"
    dest: "{{ node_directory }}latest.catchpoint"
    owner: "{{ goal_user }}"
    group: "{{ goal_user_group }}"
    mode: 0644
  become: yes
  register: catchpoint_downloaded
  when: os_family != "Windows"
  tags: node-sync

- name: retrieve the latest catchpoint
  win_get_url:
    url: "https://algorand-catchpoints.s3.us-east-2.amazonaws.com/channel/{{ algorand_network }}/latest.catchpoint"
    dest: "{{ node_directory }}latest.catchpoint"
  register: catchpoint_downloaded
  when: os_family == "Windows"
  tags: node-sync

- name: read the latest checkpoint file content
  ansible.builtin.slurp:
    src: "{{ node_directory }}latest.catchpoint"
  register: latest_catchpoint_file
  when: catchpoint_downloaded.changed
  tags: node-sync

- name: set the latest checkpoint variable
  set_fact:
    latest_catchpoint: "{{ latest_catchpoint_file['content'] | b64decode | trim }}"
  when: catchpoint_downloaded.changed
  tags: node-sync

- name: catchup node using the latest checkpoint value
  shell: "{{ goal_executable }} node catchup {{ latest_catchpoint }} -d {{ node_data_directory }}"
  args:
    chdir: "{{ node_directory }}"
  become: yes
  become_user: "{{ goal_user }}"
  when: os_family != "Windows" and catchpoint_downloaded.changed
  tags: node-sync

- name: catchup node using the latest checkpoint value
  win_command: "{{ goal_executable }} node catchup {{ latest_catchpoint }} -d {{ node_data_directory }}{{ algorand_network_base }}"
  args:
    chdir: "{{ node_directory }}{{ algorand_network_base }}"
  when: os_family == "Windows" and catchpoint_downloaded.changed
  tags: node-sync
