---
- name: retrieve the latest catchpoint
  get_url:
    url: "https://algorand-catchpoints.s3.us-east-2.amazonaws.com/channel/{{ algorand_network }}/latest.catchpoint"
    dest: "{{ node_directory }}/latest.catchpoint"
    owner: "{{ admin_user }}"
    group: "{{ admin_user_group }}"
    mode: 0644
  register: catchpoint_downloaded
  tags: node-sync

- name: read the latest checkpoint file content
  ansible.builtin.slurp:
    src: "{{ node_directory }}/latest.catchpoint"
  register: latest_catchpoint_file
  when: catchpoint_downloaded.changed
  tags: node-sync

- name: set the latest checkpoint variable
  set_fact:
    latest_catchpoint: "{{ latest_catchpoint_file['content'] | b64decode | trim }}"
  when: catchpoint_downloaded.changed
  tags: node-sync

- name: catchup node using the latest checkpoint value
  shell: "./goal node catchup {{ latest_catchpoint }} -d {{ node_directory }}/data"
  args:
    chdir: "{{ node_directory }}"
  when: catchpoint_downloaded.changed
  tags: node-sync
